name = "oliveyoung-affiliate"
type = "javascript"
main = "src/index.ts"
compatibility_date = "2026-02-09"

[build]
command = "npm run build"
cwd = "./"
assets_directory = "dist"

[env.production]
route = "k-beauty-mirror.seansim-kor.workers.dev"
zone_id = ""
