name = "k-beauty-mirror"
main = "src/index.ts"
compatibility_date = "2026-02-09"

[env.production]
route = "k-beauty-mirror.seansim-kor.workers.dev"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx", "components/**", "services/**"]
